basePath: /
host: localhost:8000
info:
  contact:
    email: Lguilhermemoreiraleite@gmail.com
    name: Guilherme Moreira
    url: github.com/LGuilhermeMoreira/
  description: this is a simple API aimed to studies.
  termsOfService: http://swagger.io/terms/
  title: API Fundamentos
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
