// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: school_service.proto

package school

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputListAllStudents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputListAllStudents) Reset() {
	*x = InputListAllStudents{}
	mi := &file_school_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputListAllStudents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputListAllStudents) ProtoMessage() {}

func (x *InputListAllStudents) ProtoReflect() protoreflect.Message {
	mi := &file_school_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputListAllStudents.ProtoReflect.Descriptor instead.
func (*InputListAllStudents) Descriptor() ([]byte, []int) {
	return file_school_service_proto_rawDescGZIP(), []int{0}
}

func (x *InputListAllStudents) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_school_service_proto protoreflect.FileDescriptor

var file_school_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x73, 0x63, 0x68, 0x6f,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x32, 0x4a, 0x0a, 0x0c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x30, 0x01,
	0x42, 0x09, 0x5a, 0x07, 0x2f, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_school_service_proto_rawDescOnce sync.Once
	file_school_service_proto_rawDescData = file_school_service_proto_rawDesc
)

func file_school_service_proto_rawDescGZIP() []byte {
	file_school_service_proto_rawDescOnce.Do(func() {
		file_school_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_school_service_proto_rawDescData)
	})
	return file_school_service_proto_rawDescData
}

var file_school_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_school_service_proto_goTypes = []any{
	(*InputListAllStudents)(nil), // 0: pb.InputListAllStudents
	(*Student)(nil),              // 1: pb.Student
}
var file_school_service_proto_depIdxs = []int32{
	0, // 0: pb.ClassService.ListAllStudents:input_type -> pb.InputListAllStudents
	1, // 1: pb.ClassService.ListAllStudents:output_type -> pb.Student
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_school_service_proto_init() }
func file_school_service_proto_init() {
	if File_school_service_proto != nil {
		return
	}
	file_school_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_school_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_school_service_proto_goTypes,
		DependencyIndexes: file_school_service_proto_depIdxs,
		MessageInfos:      file_school_service_proto_msgTypes,
	}.Build()
	File_school_service_proto = out.File
	file_school_service_proto_rawDesc = nil
	file_school_service_proto_goTypes = nil
	file_school_service_proto_depIdxs = nil
}
