# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: school.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'school.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschool.proto\x12\x02pb\"2\n\x07Student\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"H\n\tProfessor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x12\n\ndiscipline\x18\x04 \x01(\t\"T\n\x05\x43lass\x12\x1b\n\x06people\x18\x01 \x03(\x0b\x32\x0b.pb.Student\x12 \n\tprofessor\x18\x02 \x01(\x0b\x32\r.pb.Professor\x12\x0c\n\x04\x63ode\x18\x03 \x01(\tB\tZ\x07/schoolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'school_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007/school'
  _globals['_STUDENT']._serialized_start=20
  _globals['_STUDENT']._serialized_end=70
  _globals['_PROFESSOR']._serialized_start=72
  _globals['_PROFESSOR']._serialized_end=144
  _globals['_CLASS']._serialized_start=146
  _globals['_CLASS']._serialized_end=230
# @@protoc_insertion_point(module_scope)
