# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import school_pb2 as school__pb2
import school_service_pb2 as school__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in school_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClassServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAllStudents = channel.unary_stream(
                '/pb.ClassService/ListAllStudents',
                request_serializer=school__service__pb2.InputListAllStudents.SerializeToString,
                response_deserializer=school__pb2.Student.FromString,
                _registered_method=True)


class ClassServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAllStudents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAllStudents': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAllStudents,
                    request_deserializer=school__service__pb2.InputListAllStudents.FromString,
                    response_serializer=school__pb2.Student.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ClassService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ClassService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClassService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAllStudents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.ClassService/ListAllStudents',
            school__service__pb2.InputListAllStudents.SerializeToString,
            school__pb2.Student.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
