version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: api_db
    restart: always
    platform: linux/amd64

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
      MYSQL_PASSWORD: root

    ports:
      - "3306:3306"